[package]
name = "morse-code-advanced"
version = "0.1.0"
authors = ["Michael Salaverry <michael_salaverry@intuit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0.0"